# Generated by Django 4.0.5 on 2022-07-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'ordering': ['idComuna'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'ordering': ['idRegion'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUbicacion', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_ubicacion', verbose_name='Imagen')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_ubicacion.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_ubicacion.region')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubiaciones',
                'ordering': ['idUbicacion'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_ubicacion.region'),
        ),
    ]
