# Generated by Django 4.0.5 on 2022-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_medicamentos', verbose_name='Imagen'),
        ),
    ]
