# Generated by Django 4.0.5 on 2022-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'experto',
                'verbose_name_plural': 'expertos',
                'ordering': ['id'],
            },
        ),
    ]
