# Generated by Django 4.0.5 on 2022-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertos', '0003_alter_experto_options_remove_experto_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experto',
            options={'ordering': ['id'], 'verbose_name': 'experto', 'verbose_name_plural': 'expertos'},
        ),
        migrations.RemoveField(
            model_name='experto',
            name='idExperto',
        ),
        migrations.AddField(
            model_name='experto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
