# Generated by Django 4.0.5 on 2022-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertos', '0005_alter_experto_options_remove_experto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experto',
            name='idExperto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
